// Code generated by Neon - DO NOT EDIT
// https://github.com/codemicro/go-neon

package views

import (
	ntcnNxkPiCOnG "html"
	ntccdOAGbOhdV "strings"
)

func PageBegin(ctx *RenderContext) string {
	ntcRijqFUuoGg := new(ntccdOAGbOhdV.Builder)
	_, _ = ntcRijqFUuoGg.WriteString("\n<!DOCTYPE html>\n<html lang=\"en\">\n")
	_, _ = ntcRijqFUuoGg.WriteString(Head(ctx))
	_, _ = ntcRijqFUuoGg.WriteString("\n<body>\n")
	return ntcRijqFUuoGg.String()
}
func PageEnd(ctx *RenderContext) string {
	ntcRijqFUuoGg := new(ntccdOAGbOhdV.Builder)
	_, _ = ntcRijqFUuoGg.WriteString("\n</body>\n</html>\n")
	return ntcRijqFUuoGg.String()
}
func Head(ctx *RenderContext) string {
	ntcRijqFUuoGg := new(ntccdOAGbOhdV.Builder)
	_, _ = ntcRijqFUuoGg.WriteString("\n<head>\n    <meta charset=\"UTF-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n    <title>")
	_, _ = ntcRijqFUuoGg.WriteString(ntcnNxkPiCOnG.EscapeString(ctx.pageTitle))
	_, _ = ntcRijqFUuoGg.WriteString("</title>\n    <link rel=\"stylesheet\" href=\"")
	_, _ = ntcRijqFUuoGg.WriteString(ntcnNxkPiCOnG.EscapeString(ctx.externalURL))
	_, _ = ntcRijqFUuoGg.WriteString("/css/main.css\">\n</head>\n")
	return ntcRijqFUuoGg.String()
}
func Navbar(ctx *RenderContext) string {
	ntcRijqFUuoGg := new(ntccdOAGbOhdV.Builder)
	_, _ = ntcRijqFUuoGg.WriteString("\n<div class=\"pt\"></div>\n<nav class=\"top-nav\">\n    <h1 class=\"name\">BurntPocket</h1>\n</nav>\n")
	return ntcRijqFUuoGg.String()
}
