// Code generated by Neon - DO NOT EDIT
// https://github.com/codemicro/go-neon

package views

import (
	"github.com/codemicro/abigit/abigit/urls"
	ntcnNxkPiCOnG "html"
	ntccdOAGbOhdV "strings"
)

func PageBegin(ctx *RenderContext) string {
	ntcRijqFUuoGg := new(ntccdOAGbOhdV.Builder)
	_, _ = ntcRijqFUuoGg.WriteString("\n    <!DOCTYPE html>\n    <html lang=\"en\">\n    ")
	_, _ = ntcRijqFUuoGg.WriteString(Head(ctx))
	_, _ = ntcRijqFUuoGg.WriteString("\n    <body>\n")
	return ntcRijqFUuoGg.String()
}
func PageEnd(ctx *RenderContext) string {
	ntcRijqFUuoGg := new(ntccdOAGbOhdV.Builder)
	_, _ = ntcRijqFUuoGg.WriteString("\n    </body>\n    </html>\n")
	return ntcRijqFUuoGg.String()
}
func Head(ctx *RenderContext) string {
	ntcRijqFUuoGg := new(ntccdOAGbOhdV.Builder)
	_, _ = ntcRijqFUuoGg.WriteString("\n    <head>\n        <meta charset=\"UTF-8\">\n        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n        <title>")
	_, _ = ntcRijqFUuoGg.WriteString(ntcnNxkPiCOnG.EscapeString(ctx.pageTitle))
	_, _ = ntcRijqFUuoGg.WriteString("</title>\n        <link rel=\"stylesheet\" href=\"")
	_, _ = ntcRijqFUuoGg.WriteString(ntcnNxkPiCOnG.EscapeString(urls.Make(`/css/main.css`)))
	_, _ = ntcRijqFUuoGg.WriteString("\">\n        <script src=\"")
	_, _ = ntcRijqFUuoGg.WriteString(ntcnNxkPiCOnG.EscapeString(urls.Make(`/js/htmx.min.js`)))
	_, _ = ntcRijqFUuoGg.WriteString("\"></script>\n    </head>\n")
	return ntcRijqFUuoGg.String()
}
func Navbar(ctx *RenderContext) string {
	ntcRijqFUuoGg := new(ntccdOAGbOhdV.Builder)
	_, _ = ntcRijqFUuoGg.WriteString("\n    <div class=\"pt\"></div>\n    <nav class=\"top-nav\">\n        <h1 class=\"name\">")
	_, _ = ntcRijqFUuoGg.WriteString(ntcnNxkPiCOnG.EscapeString(ctx.platformName))
	_, _ = ntcRijqFUuoGg.WriteString("</h1>\n\n        ")
	if !ctx.reducedContent {
		_, _ = ntcRijqFUuoGg.WriteString("\n            ")
		if ctx.isAuthed() {
			_, _ = ntcRijqFUuoGg.WriteString("\n                <a href=\"")
			_, _ = ntcRijqFUuoGg.WriteString(ntcnNxkPiCOnG.EscapeString(urls.Make(urls.CreateRepository)))
			_, _ = ntcRijqFUuoGg.WriteString("\">New repository</a>\n            ")
		} else {
			_, _ = ntcRijqFUuoGg.WriteString("\n                <a href=\"")
			_, _ = ntcRijqFUuoGg.WriteString(ntcnNxkPiCOnG.EscapeString(urls.Make(urls.AuthLogin)))
			_, _ = ntcRijqFUuoGg.WriteString("\">Login</a>\n            ")
		}
		_, _ = ntcRijqFUuoGg.WriteString("\n        ")
	}
	_, _ = ntcRijqFUuoGg.WriteString("\n    </nav>\n    <div class=\"pt\"></div>\n")
	return ntcRijqFUuoGg.String()
}
func ProblemBox(problem string) string {
	ntcRijqFUuoGg := new(ntccdOAGbOhdV.Builder)
	_, _ = ntcRijqFUuoGg.WriteString("\n    <p style=\"color: red\">")
	_, _ = ntcRijqFUuoGg.WriteString(ntcnNxkPiCOnG.EscapeString(problem))
	_, _ = ntcRijqFUuoGg.WriteString("</p>\n")
	return ntcRijqFUuoGg.String()
}
