// Code generated by Neon - DO NOT EDIT
// https://github.com/codemicro/go-neon

package views

import (
	"github.com/codemicro/abigit/abigit/urls"
	ntcbutTMxUNta "html"
	ntcckNmMSvBZg "strings"
)

type CreateRepositoryProps struct {
	Problem string
}

func CreateRepository(ctx *RenderContext, props *CreateRepositoryProps) string {
	ntcRijqFUuoGg := new(ntcckNmMSvBZg.Builder)
	_, _ = ntcRijqFUuoGg.WriteString("\n\n    ")
	pageTitle := "Create a new repository"
	ctx.pageTitle = pageTitle + " | " + ctx.platformName

	_, _ = ntcRijqFUuoGg.WriteString("\n\n    ")
	_, _ = ntcRijqFUuoGg.WriteString(PageBegin(ctx))
	_, _ = ntcRijqFUuoGg.WriteString("\n    ")
	_, _ = ntcRijqFUuoGg.WriteString(Navbar(ctx))
	_, _ = ntcRijqFUuoGg.WriteString("\n\n    <div class=\"container\">\n        <h3>")
	_, _ = ntcRijqFUuoGg.WriteString(ntcbutTMxUNta.EscapeString(pageTitle))
	_, _ = ntcRijqFUuoGg.WriteString("</h3>\n\n        ")
	if props.Problem != "" {
		_, _ = ntcRijqFUuoGg.WriteString("\n            ")
		_, _ = ntcRijqFUuoGg.WriteString(ProblemBox(props.Problem))
		_, _ = ntcRijqFUuoGg.WriteString("\n        ")
	}
	_, _ = ntcRijqFUuoGg.WriteString("\n\n        <form action=\"\" method=\"post\">\n            <div>\n                <label for=\"name\">Name</label>\n                <input type=\"text\" name=\"name\" id=\"name\" required\n                    hx-post=\"")
	_, _ = ntcRijqFUuoGg.WriteString(ntcbutTMxUNta.EscapeString(urls.Make(urls.CreateRepositoryValidation)))
	_, _ = ntcRijqFUuoGg.WriteString("\"\n                    hx-trigger=\"keyup changed delay:250ms\"\n                    hx-target=\"#validation-output\"\n                >\n                <span class=\"message\" style=\"padding-left: 10px\" id=\"validation-output\"></span>\n            </div>\n            <div>\n                <input type=\"submit\" value=\"Create\">\n            </div>\n        </form>\n\n    </div>\n\n    ")
	_, _ = ntcRijqFUuoGg.WriteString(PageEnd(ctx))
	_, _ = ntcRijqFUuoGg.WriteString("\n\n")
	return ntcRijqFUuoGg.String()
}
