// Code generated by Neon - DO NOT EDIT
// https://github.com/codemicro/go-neon

package views

import (
	"fmt"
	"github.com/codemicro/abigit/abigit/urls"
	ntcHLddPVlKfQ "html"
	ntcQYuyrNqZqe "strconv"
	ntcnPUUcSzrqK "strings"
)

type ErrorProps struct {
	StatusCode       int
	ExtraInformation string
}

func Error(ctx *RenderContext, props *ErrorProps) string {
	ntcRijqFUuoGg := new(ntcnPUUcSzrqK.Builder)
	_, _ = ntcRijqFUuoGg.WriteString("\n\n    ")
	ctx.pageTitle = fmt.Sprintf("%d %s | %s", props.StatusCode, statusMessages[props.StatusCode], ctx.platformName)
	ctx.reducedContent = true

	_, _ = ntcRijqFUuoGg.WriteString("\n\n    ")
	_, _ = ntcRijqFUuoGg.WriteString(PageBegin(ctx))
	_, _ = ntcRijqFUuoGg.WriteString("\n    ")
	_, _ = ntcRijqFUuoGg.WriteString(Navbar(ctx))
	_, _ = ntcRijqFUuoGg.WriteString("\n\n    <div class=\"container\">\n        <h3>")
	_, _ = ntcRijqFUuoGg.WriteString(ntcQYuyrNqZqe.FormatInt(int64(props.StatusCode), 10))
	_, _ = ntcRijqFUuoGg.WriteString(" ")
	_, _ = ntcRijqFUuoGg.WriteString(ntcHLddPVlKfQ.EscapeString(statusMessages[props.StatusCode]))
	_, _ = ntcRijqFUuoGg.WriteString("</h3>\n\n        ")
	if props.ExtraInformation != "" {
		_, _ = ntcRijqFUuoGg.WriteString("\n            <p>")
		_, _ = ntcRijqFUuoGg.WriteString(ntcHLddPVlKfQ.EscapeString(props.ExtraInformation))
		_, _ = ntcRijqFUuoGg.WriteString("</p>\n        ")
	}
	_, _ = ntcRijqFUuoGg.WriteString("\n\n        ")
	if props.StatusCode == 401 {
		_, _ = ntcRijqFUuoGg.WriteString("\n            <a href=\"")
		_, _ = ntcRijqFUuoGg.WriteString(ntcHLddPVlKfQ.EscapeString(urls.Make(urls.AuthLogin)))
		_, _ = ntcRijqFUuoGg.WriteString("\">Click here to login.</a>\n        ")
	}
	_, _ = ntcRijqFUuoGg.WriteString("\n    </div>\n\n    ")
	_, _ = ntcRijqFUuoGg.WriteString(PageEnd(ctx))
	_, _ = ntcRijqFUuoGg.WriteString("\n\n")
	return ntcRijqFUuoGg.String()
}
